# Generated by Django 5.2.3 on 2025-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("public_date", models.DateField()),
                ("image", models.ImageField(upload_to="images")),
                ("body", models.TextField()),
            ],
        ),
    ]
