# Generated by Django 5.2.3 on 2025-07-02 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="public_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
