# Generated by Django 5.2.3 on 2025-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_public_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="public_date",
            field=models.DateTimeField(),
        ),
    ]
